# Installs Python dependencies, runs tests and lints (via flake8) with a specific version of Python

name: Collaboration flake8 Linter

on: [push, pull_request]

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 . --statistics --show-source
